### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by dbarbuzzi** [elijahr/elvish-python-venv#1]
It appears that this module does not properly support Windows. The commands don’t fail, however, the `activate` function assumes that the binary directory in the venv folder is `bin` when, on Windows, that folder is instead named `Scripts` (e.g., `.venv/Scripts` instead of `.venv/bin`). As a result, the wrong folder is prepended to the path list.

If this project is still active/open to PRs, I’d gladly open one with a local fix I’ve created.

**Comment by elijahr** [comment]
@dbarbuzzi please feel free to open a pull request with your fix, that would be great!
